### ISSUE TITLE
panic: cannot allocate memory

### ISSUE THREAD

**Issue by withlin** [glenn-wang/xdp_acl#1]
### 不能分配内存？
```
root@host-10-102-126-64:/xdp_acl# uname -r
5.4.0-84-generic

root@host-10-102-126-64:/xdp_acl# ./xdp_acl  -D eth0
Load XDP in AUTO mode
Welcome to XDP ACL
panic: cannot allocate memory

goroutine 1 [running]:
main.loadXdpOnLink()
	/xdp_acl/xdp_about.go:99 +0x17e
main.main()
	/xdp_acl/main.go:87 +0x190
```

**Comment by glenn-wang** [comment]
> ### 不能分配内存？
> ```
> root@host-10-102-126-64:/xdp_acl# uname -r
> 5.4.0-84-generic
> 
> root@host-10-102-126-64:/xdp_acl# ./xdp_acl  -D eth0
> Load XDP in AUTO mode
> Welcome to XDP ACL
> panic: cannot allocate memory
> 
> goroutine 1 [running]:
> main.loadXdpOnLink()
> 	/xdp_acl/xdp_about.go:99 +0x17e
> main.main()
> 	/xdp_acl/main.go:87 +0x190
> ```

试一下下面的启动命令，看是否还报错？

```
./xdp_acl  -D eth0 -S
```

**Comment by withlin** [comment]
@glenn-wang  it work for me fine.  :)

**Comment by glenn-wang** [comment]
```
$ ethtool -i eth0 
```
使用上面的命令查看下你的网卡驱动信息，如果是 virtio，需要 cpu 核心数是 网卡队列数的两倍或者更多，Native 模式才能工作。

-----------------------------------
若网卡支持Native模式，下面的命令会优先以 Native模式加载。但如果碰巧是 virtio 网卡，并且cpu 核心数不足网卡队列数的两倍，则会报错。所以，最好显式指明加载方式。
```
$ ./xdp_acl -D eth0
```

**Comment by withlin** [comment]
> 使用上面的命令查看下你的网卡驱动信息，如果是 virtio，需要 cpu 核心数是 网卡队列数的两倍或者更多，Native 模式才能工作。

为什么驱动是`virtio_net`模式，需要 cpu 核心数是 网卡队列数的两倍或者更多呢？xdp文档是这么说的么？

@glenn-wang ping

**Comment by glenn-wang** [comment]
> > 使用上面的命令查看下你的网卡驱动信息，如果是 virtio，需要 cpu 核心数是 网卡队列数的两倍或者更多，Native 模式才能工作。
> 
> 为什么驱动是`virtio_net`模式，需要 cpu 核心数是 网卡队列数的两倍或者更多呢？xdp文档是这么说的么？
> 
> @glenn-wang ping

之前遇到这个问题，网上查到的，希望下面两个链接能帮到你。

https://marc.info/?l=xdp-newbies&m=157431759821123

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=672aafd5d88a

**Comment by withlin** [comment]
@glenn-wang hello,方便加个wechat么？
